server:
    port: ${PORT:8080}
    socketOptions:
        keepAlive: 100
        connectTimeoutMS: 30000
    error:
        include-message: always

spring:
    data:
        mongodb:
            uri: ${URI_MONGODB}
            database: localizapet
            authentication-database: admin

localizapet:
    app:
        jwtTokenName: LocalizaToken
        jwtSecret: localizapetSecretcv834nv8sahnvu89shnvuiasdnhvuisadhnvuiasdnhvuidasnhvuai
        jwtExpirationMs: 86400000
